version: '3.4'

services:
  web:
    container_name: xalok-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: xalok-php
    build:
      context: ./.docker/php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

  database:
    container_name: xalok-postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=xalok
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data: